# OpenCV Basics

In [1]:
# Importing packages
import numpy as np
import cv2

# Read, Show and Write Images

In [3]:
img = cv2.imread('House_n_Nature.jpg')

[[[196  87   1]
  [196  87   2]
  [196  87   2]
  ...
  [197 118  61]
  [190 111  54]
  [174 104  45]]

 [[196  87   1]
  [196  87   2]
  [196  87   2]
  ...
  [187 109  50]
  [179 101  42]
  [172  99  41]]

 [[196  87   1]
  [196  87   2]
  [197  88   3]
  ...
  [177 102  40]
  [180 105  43]
  [179 106  48]]

 ...

 [[185 105  40]
  [185 107  41]
  [186 108  42]
  ...
  [ 22 187 136]
  [ 31 185 136]
  [ 13 153 106]]

 [[187 109  43]
  [188 110  44]
  [189 111  45]
  ...
  [ 20 183 132]
  [ 38 191 140]
  [ 19 160 111]]

 [[189 111  45]
  [190 112  46]
  [192 114  48]
  ...
  [ 21 181 129]
  [ 39 190 140]
  [ 20 158 110]]]


### ***** END OF FILE ***********************************